### ISSUE TITLE
Incorrect ASCII result in console using Visual Studio Community 2015

### ISSUE THREAD

**Issue by ELNEVO** [Daivuk/amg#1]
@Daivuk I tried your code in Visual Studio Community 2015 and the result does not get printed correctly in the console.

This is the result I get:
![obama_in_ascii](https://cloud.githubusercontent.com/assets/4079590/19622029/45d54fb2-9876-11e6-8152-e0e200a437a2.png)

Could you please look into it?
Thanks in advance.

**Comment by Daivuk** [comment]
Thanks for logging the bug.
Tested in VS2013 and the issue is also present. It seems to be a windows 10 thing and not a visual studio version. I need a line return.

**Comment by Daivuk** [comment]
Fixed

**Comment by ELNEVO** [comment]
Thank you for the quick fix. I appreciate your work. Keep it up.
